# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 200fb6ae9410a1c008c66965e37fcae3c2a63e2fdb968f817cfa6e5e20e5e7e58378c4eb357abe6a27b4474c03100200a8c0af33f29437226570933bf3252e0e

test:
  secret_key_base: 9a38cd3ac18a05f8faaf9c34daf6e48024df4080da86d24fd4d7a99d1fdf0472110ff29a281de67747e66161e15df528cf238cfa97c1b191e236ad7c0a84ea20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
